name: Test cocobasy
on: [ push ]
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.19.2

      - name: Test Deno has been setup
        run: deno run https://deno.land/std/examples/welcome.ts

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner and deno has been installed"
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name Run linter
        run: deno lint

      - run: echo "🍏 This job's status is ${{ job.status }}."

